apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::829688972105:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FS3GTL4NFR0Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::829688972105:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-13T12:14:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-13T12:14:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1669"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dd05dfb2-3636-4533-9a33-270d9f813eb5
